runtime: php83 
service: default 

handlers:

- url: /assets
  static_dir: assets
  secure: always

- url: /css
  static_dir: css
  secure: always

- url: /js
  static_dir: js
  secure: always


- url: /(.*\.(gif|png|jpg|ico|html|php))$
  script: auto
  secure: always


- url: /.*
  script: auto
  secure: always